### CURSO DE MANIPULACIÓN Y TRANSFORMACIÓN DE DATOS CON PANDAS Y NUMPY

In [2]:
#Importamos las librerías a emplear
import numpy as np
import pandas as pd

In [21]:
#Empezamos creando una lista de Python
ls = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print("Lista: ", ls)
print("Tipo de dato: ", type(ls))

Lista:  [1, 2, 3, 4, 5, 6, 7, 8, 9]
Tipo de dato:  <class 'list'>


In [22]:
#Creamos un array con Numpy
arr = np.array(ls)
print("Array: ", arr)
print("Tipo de dato: ", type(arr))

Array:  [1 2 3 4 5 6 7 8 9]
Tipo de dato:  <class 'numpy.ndarray'>


In [26]:
#Trabajamos con una matriz (sigue siendo una lista de python)
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print("Matriz: ", matrix)
print("Tipo de dato: ", type(matrix))

Matriz:  [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Tipo de dato:  <class 'list'>


In [27]:
#Lo pasamos a un array
mat = np.array(matrix)
print("Matriz: ", mat)
print("Tipo de dato: ", type(mat))

Matriz:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Tipo de dato:  <class 'numpy.ndarray'>


In [29]:
#Accedemos mediante índices
print("Valor en el índice 0:", arr[0])
print("arr[1]+arr[4]=", arr[1] + arr[4])

Valor en el índice 0: 1
arr[1]+arr[4]= 7


In [38]:
#Otros ejemplos
print("Accedemos a la 1ra fila:", mat[0])
print("Accedemos al valor [0][2]:", mat[0, 2])
print("Accedemos al valor [:][2]:", mat[:, 2])
print("Accedemos al valor [1][1:]:", mat[1, 1:])
print("Accedemos al valor [-1][2]:", mat[-1, 2])

Accedemos a la 1ra fila: [1 2 3]
Accedemos al valor [0][2]: 3
Accedemos al valor [:][2]: [3 6 9]
Accedemos al valor [1][1:]: [5 6]
Accedemos al valor [-1][2]: 9


#### TIPO DE DATOS

In [50]:
#Definimos un nuevo array
arr = np.array([1, 2, 3, 4])
arr.dtype

dtype('int32')

In [51]:
#Declaramos un array con un tipo de dato específico
arr = np.array([1, 2, 3, 4], dtype='float64')
arr.dtype

dtype('float64')

In [52]:
#Cambiamos el tipo de dato de nuestro array a int32
arr = arr.astype(np.int32)
arr

array([1, 2, 3, 4])

In [53]:
#Cambiamos el tipo de dato a booleano
arr = np.array([0, 1, 2, 3, 4])
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True])

In [54]:
#Cambiamos el tipo de dato a string
arr = np.array([0, 1, 2, 3, 4])
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S11')

In [55]:
#Cambiamos el tipo de dato a número
arr = arr.astype(np.int8)
arr

array([0, 1, 2, 3, 4], dtype=int8)

#### DIMENSIONES

In [75]:
#Escalar: Un solo dato o valor
scalar = np.array(6)
print("Escalar:", scalar)
print("Dimention:", scalar.ndim)

Escalar: 6
Dimention: 0


In [76]:
#Vector: Listas de Python
vector = np.array([1, 2, 3], dtype="float64")
print("Vector:", vector)
print("Dimention:", vector.ndim)

Vector: [1. 2. 3.]
Dimention: 1


In [77]:
#Matriz: Hoja de cálculo
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matriz:", matrix)
print("Dimention:", matrix.ndim)

Matriz: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimention: 2


In [78]:
#Tensor: Series de tiempo o imágenes
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],
                   [[13, 13, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]])
print("Tensor:", tensor)
print("Dimention:", tensor.ndim)

Tensor: [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 13 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]
Dimention: 3


In [79]:
#Definimos el número de dimensiones
x = np.array([1, 2, 3], ndmin = 10)
print("Array:", x)

Array: [[[[[[[[[[1 2 3]]]]]]]]]]


In [80]:
#Sumamos 1 dimensión para las filas
expand = np.expand_dims(np.array([1, 2, 3]), axis=0)
print("Array:", expand)
print("Dimention:", expand.ndim)

Array: [[1 2 3]]
Dimention: 2


In [74]:
#Comprimimos al número necesario de dimensiones
print(expand, expand.ndim) 
expand_2 = np.squeeze(expand)
print(expand_2, expand_2.ndim)

[[1 2 3]] 2
[1 2 3] 1


#### CREACIÓN DE ARRAYS

In [82]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [86]:
np.zeros(3)

array([0., 0., 0.])

In [87]:
np.zeros((10, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [88]:
np.ones(2)

array([1., 1.])

In [89]:
np.ones((4, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [90]:
#CREAMOS UN ARRAY DEFINIENDO UN INICIO, FINAL Y NÚMERO DE DIVISIONES
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [91]:
#MATRIZ DIAGONAL
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [92]:
#NÚMEROS ALEATORIOS
np.random.rand()

0.4856636805348883

In [93]:
#VECTORES ALEATORIOS
np.random.rand(4)

array([0.5463161 , 0.95059586, 0.95374912, 0.58018586])

In [94]:
#MATRICES ALEATORIAS
np.random.rand(5, 5)

array([[0.12169381, 0.29542039, 0.28547597, 0.3797425 , 0.7975034 ],
       [0.65174875, 0.41403071, 0.80503563, 0.81627149, 0.93103549],
       [0.01940557, 0.12369107, 0.01985543, 0.00326161, 0.2586638 ],
       [0.44228448, 0.40805546, 0.1991467 , 0.54569706, 0.39748257],
       [0.57309175, 0.87298048, 0.46209241, 0.90316399, 0.20191642]])

In [95]:
#NÚMERO ENTERO ALEATORIO ENTRE X & Y
np.random.randint(1, 15)

10

In [96]:
#HACEMOS LO ANTERIOR PARA UNA MATRIZ
np.random.randint(1, 15, (3, 3))

array([[ 5,  1, 11],
       [ 2,  8,  9],
       [12,  4,  8]])

#### SHAPE AND RESHAPE

In [103]:
#Creamos una matriz de 3x2
arr = np.random.randint(1, 10, (3, 2))
print("Dimention:", arr.shape)
arr

Dimention: (3, 2)


array([[8, 2],
       [3, 8],
       [1, 9]])

In [108]:
#Transformamos el arreglo
arr.reshape(1, 6)
#arr.reshape(2, 3)

array([[8, 2, 3, 8, 1, 9]])

In [109]:
#RESHAPE en "C"
np.reshape(arr, (2, 3), 'C')

array([[8, 2, 3],
       [8, 1, 9]])

In [110]:
#RESHAPE en Fortran
np.reshape(arr, (2, 3), 'F')

array([[8, 1, 8],
       [3, 2, 9]])

In [111]:
#RESHAPE optimizado
np.reshape(arr, (2, 3), 'A')

array([[8, 2, 3],
       [8, 1, 9]])

#### FUNCIONES PRINCIPALES

In [7]:
#Definimos un array aleatorio
x = np.random.randint(1, 20, 10)
print("Array:", x)

y = x.reshape(2, 5)
print("Matriz:", y)

Array: [15 13 13 13  1  7 16  2 18 12]
Matriz: [[15 13 13 13  1]
 [ 7 16  2 18 12]]


In [11]:
print("Valor máximo de x:", x.max())
print("Valor máximo de y (columnas):", y.max(0))

Valor máximo de x: 18
Valor máximo de y (columnas): [15 16 13 18 12]


In [14]:
#Posición de un elemento
print("Posición del número mayor:", x.argmax())

Posición del número mayor: 8


In [16]:
#Más ejemplos
print(x.min())
print(x.argmin())
print(y.min(0))
print(y.argmin(0))

1
4
[ 7 13  2 13  1]
[1 0 1 0 0]


In [17]:
#Distancia entre el valor más bajo con el más alto
x.ptp()

17

#### ANÁLISIS ESTADÍSTICO

In [19]:
#Ordenar los elementos
x.sort()
x

array([ 1,  2,  7, 12, 13, 13, 13, 15, 16, 18])

In [20]:
#Obtener un percentil
np.percentile(x, 50)

13.0

In [21]:
#Mediana
np.median(x)

13.0

In [22]:
#Desviación estándar
np.std(x)

5.477225575051661

In [25]:
#Varianza
np.var(y, 0)

array([36.  , 30.25, 16.  ,  4.  ,  6.25])

In [26]:
#Promedio
np.mean(y, 1)

array([ 7., 15.])